apiVersion: triggers.tekton.dev/v1
kind: EventListener
metadata:
  name: mq-qm-post-stage
spec:
  serviceAccountName: pipeline
  triggers:
    - name: mq-qm-post-stage
      template:
        ref: mq-qm-post-stage
