apiVersion: triggers.tekton.dev/v11
kind: EventListener
metadata:
  name: mq-spring-app-post-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - name: mq-spring-app-post-dev
      template:
        ref: mq-spring-app-post-dev
